server:
  port: 9090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
         - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: card-service
          uri: lb://card-service/
          predicates:
            - Path=/cards/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: transaction-service
          uri: lb://transaction-service/
          predicates:
            - Path=/transactions/**
          filters:
            - RemoveRequestHeader=Cookie
      
