server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dhmoney
    username: grupo9
    password: grupo9
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dll-auto: update
    show-sql: true
    datasource:
      url: jdbc:mysql://localhost:3306/dhmoney
      username: grupo9
      password: grupo9
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${d-h-m.keycloak.serverUrl}/realms/${d-h-m.keycloak.realm}
            jwk-set-uri: ${d-h-m.keycloak.serverUrl}/realms/${d-h-m.keycloak.realm}/protocol/openid-connect/certs
          client:
            registration:
              users-client:
                provider: keycloak
                client-id: ${d-h-m.keycloak.clientId}
                client-secret: ${d-h-m.keycloak.clientSecret}
                authorization-grant-type: client_credentials
              provider:
                users-client:
                  issuer-uri: ${d-h-m.keycloak.serverUrl}/realms/${d-h-m.keycloak.realm}
                  jwk-set-uri: ${d-h-m.keycloak.serverUrl}/realms/${d-h-m.keycloak.realm}/protocol/openid-connect/certs
